### ISSUE TITLE
avvio container govway:3.3.14_postgres con db distinti : errore relation db_info_console inesistente

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway#160]
**Descrizione del Bug**
```
pg-1  | 2024-03-29 12:07:39.922 GMT [82] WARNING:  there is already a transaction in progress
pg-1  | 2024-03-29 12:08:33.569 GMT [86] ERROR:  relation "db_info_console" does not exist at character 15
pg-1  | 2024-03-29 12:08:33.569 GMT [86] STATEMENT:  select * from db_info_console order by id DESC
```

**Come riprodurlo:**

Partendo da una orchestrazione tramite docker-compose del tipo 

```yaml
services:
  gw:
    image: linkitaly/govway:3.3.14_postgres
    env_file: .env_pg
    depends_on:
        - pg
  pg: 
      image: postgres:16
```

dove `.env_pg` contiene la definizione delle variabili relative all'uso di 4 database distinti (db, stat, conf, trac)
all'avvio dell'applicativo, durante la fase di popolamento degli schemi si registra l'errore di cui sopra

Mentre con la stessa configurazione con l'utilizzo di un unico database l'errore non si verifica.

**Risultato atteso:**

Nessun errore registrato dal popolamento degli schemi dei diversi database, come quando l'applicativo viene avviato con un unico db.
